# Query -> Hallucinated Classification -> Real Classification

We previously constrained the LLM to a set of outputs using `Literal` what if we just ask the LLM to return a fake classification that looks like one of ours. Then we use an embedding to resolve to the "real" entity.

We can do this when we have a large-ish set of labels (brands, etc) to do a kind of large multi-label classification

**Refinement** -- Let the model hallucinate a classification, then do an embedding lookup to get a real classification

## Boilerplate

Install deps, mount GDrive, prompt for your OpenAI Key (placed in your GDrive)

In [18]:
import os
os.environ["CHEAT_AT_SEARCH_DATA_PATH"] = "/home/jovyan/data"

from cheat_at_search.data_dir import mount
mount(use_gdrive=False)
from cheat_at_search.search import run_strategy, ndcgs, ndcg_delta
from cheat_at_search.wands_data import products, judgments

CAT_SEP = "/"

products

,product_id,product_name,product_class,category hierarchy,product_description,product_features,rating_count,average_rating,review_count,features,...,description,category,sub_category,cat_subcat,product_name_snowball,product_description_snowball,subcategory,category_snowball,subcategory_snowball,cat_subcat_snowball
0,0,solid wood platform bed,Beds,Furniture / Bedroom Furniture / Beds & Headboa...,"good , deep sleep can be quite difficult to ha...",overallwidth-sidetoside:64.7|dsprimaryproducts...,15.0,4.5,15.0,"[overallwidth-sidetoside:64.7, dsprimaryproduc...",...,"good , deep sleep can be quite difficult to ha...",Furniture,Bedroom Furniture,FurnitureBedroom Furniture,"Terms({'wood', 'platform', 'solid', 'bed'})","Terms({'s', 'good', 'after', 'space', 'kaylin'...",Bedroom Furniture,Terms({'furnitur'}),"Terms({'bedroom', 'furnitur'})","Terms({'furnitur', 'furniturebedroom'})"
1,1,all-clad 7 qt . slow cooker,Slow Cookers,Kitchen & Tabletop / Small Kitchen Appliances ...,"create delicious slow-cooked meals , from tend...",capacityquarts:7|producttype : slow cooker|pro...,100.0,2.0,98.0,"[capacityquarts:7, producttype : slow cooker, ...",...,"create delicious slow-cooked meals , from tend...",Kitchen & Tabletop,Small Kitchen Appliances,Kitchen & TabletopSmall Kitchen Appliances,"Terms({'clad', 'slow', '7', 'qt', 'cooker', 'a...","Terms({'s', 'soup', 'meat', 'dessert', 'presen...",Small Kitchen Appliances,"Terms({'kitchen', 'tabletop'})","Terms({'applianc', 'kitchen', 'small'})","Terms({'tabletopsmal', 'kitchen', 'applianc'})"
2,2,all-clad electrics 6.5 qt . slow cooker,Slow Cookers,Kitchen & Tabletop / Small Kitchen Appliances ...,prepare home-cooked meals on any schedule with...,features : keep warm setting|capacityquarts:6....,208.0,3.0,181.0,"[features : keep warm setting, capacityquarts:...",...,prepare home-cooked meals on any schedule with...,Kitchen & Tabletop,Small Kitchen Appliances,Kitchen & TabletopSmall Kitchen Appliances,"Terms({'clad', '6', 'slow', 'qt', '5', 'electr...","Terms({'on', 'slow', '26', 'schedul', 'ani', '...",Small Kitchen Appliances,"Terms({'kitchen', 'tabletop'})","Terms({'applianc', 'kitchen', 'small'})","Terms({'tabletopsmal', 'kitchen', 'applianc'})"
3,3,all-clad all professional tools pizza cutter,"Slicers, Peelers And Graters",Browse By Brand / All-Clad,this original stainless tool was designed to c...,overallwidth-sidetoside:3.5|warrantylength : l...,69.0,4.5,42.0,"[overallwidth-sidetoside:3.5, warrantylength :...",...,this original stainless tool was designed to c...,Browse By Brand,All-Clad,Browse By BrandAll-Clad,"Terms({'clad', 'cutter', 'pizza', 'tool', 'pro...","Terms({'s', 'cookwar', 'pizza', 'crust', 'doug...",All-Clad,"Terms({'by', 'brand', 'brows'})","Terms({'clad', 'all'})","Terms({'by', 'clad', 'brows', 'brandal'})"
4,4,baldwin prestige alcott passage knob with roun...,Door Knobs,Home Improvement / Doors & Door Hardware / Doo...,the hardware has a rich heritage of delivering...,compatibledoorthickness:1.375 '' |countryofori...,70.0,5.0,42.0,"[compatibledoorthickness:1.375 '' , countryofo...",...,the hardware has a rich heritage of delivering...,Home Improvement,Doors & Door Hardware,Home ImprovementDoors & Door Hardware,"Terms({'passag', 'knob', 'alcott', 'rosett', '...","Terms({'on', 'creat', 'has', 'is', 'privaci', ...",Doors & Door Hardware,"Terms({'improv', 'home'})","Terms({'hardwar', 'door'})","Terms({'home', 'door', 'improvementdoor', 'har..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42989,42989,malibu pressure balanced diverter fixed shower...,Shower Panels,Home Improvement / Bathroom Remodel & Bathroom...,the malibu pressure balanced diverter fixed sh...,producttype : shower panel|spraypattern : rain...,3.0,4.5,2.0,"[producttype : shower panel, spraypattern : ra...",...,the malibu pressure balanced diverter fixed sh...,Home Improvement,Bathroom Remodel & Bathroom Fixtures,Home ImprovementBathroom Remodel & Bathroom Fi...,"Terms({'head', 'shower', 'pressur', 'fix', 'ma...","Terms({'shower', 'turn', 'is', 'sleek', 'an', ...",Bathroom Remodel & Bathroom Fixtures,"Terms({'improv', 'home'})","Terms({'remodel', 'fixtur', 'bathroom'})","Terms({'remodel', 'home', 'improvementbathroom..."
42990,42990,emmeline 5 piece breakfast dining set,Dining Table Sets,Furniture / Kitchen & Dining Furniture / Dinin...,,basematerialdetails : steel| : gray wood|ofhar...,1314.0,4.5,864.0,"[basematerialdetails : steel, : gray wood, of...",...,,Furniture,Kitchen & Dining Furniture,FurnitureKitchen & Dining Furniture,"Terms({'emmelin', 'breakfast', '5', 'dine', 's...",Terms(set()),Kitchen & Dining Furniture,Terms({'furnitur'}),"Terms({'dine', 'kitchen', 'furnitur'})","Terms({'dine', 'furnitur', 'furniturekitchen'})"
42991,42991,maloney 3 piece pub table set,Dining Table Sets,Furniture / Kitchen & Dining Furniture / Dinin...,this pub table set includes 1 counter height t...,additionaltoolsrequirednotincluded : power dri...,49.0,4.0,41.0,[additionaltoolsrequirednotincluded : power dr...,...,this pub table set includes 1 counter height t...,Furniture,Kitchen & Dining Furniture,FurnitureKitchen & Dining Furniture,"Terms({'3', 'tabl', 'maloney', 'piec', 'set', ...","Terms({'locat', 's', 'room', 'stool', 'put', '...",Kitchen & Dining Furniture,Terms({'furnitur'}),"Terms({'dine', 'kitchen', 'furnitur'})","Terms({'dine', 'furnitur', 'furniturekitchen'})"
42992,42992,fletcher 27.5 '' wide polyester armchair,Teen Lounge Furniture|Accent Chairs,Furniture / Living Room Furniture / Chairs & S...,"bring iconic , modern style to your space in a...",legmaterialdetails : rubberwood|backheight-sea...,1746.0,4.5,1226.0,"[legmaterialdetails : rubberwood, backheight-s...",...,"bring iconic , modern style to your space in a...",Furniture,Living Room Furniture,FurnitureLiving Room Furniture,"Terms({'wide', 'fletcher', '27', 'polyest', '5...","Terms({'s', 'sinuous', 'for', 'space', 'polyes...",Living Room Furniture,Terms({'furnitur'}),"Terms({'room', 'furnitur', 'live'})","Terms({'room', 'furnitureliv', 'furnitur'})"
42993,42993,griffin 29 '' bar stool,Bar Stools,Furniture / Kitchen & Dining Furniture / Bar F...,this set of two barstools features a minimalis...,distancebetweenfloorandfootrest:7.5|dssecondar...,20.0,4.5,20.0,"[distancebetweenfloorandfootrest:7.5, dssecond...",...,this set of two barstools features a minimalis...,Furniture,Kitchen & Dining Furniture,FurnitureKitchen & Dining Furniture,"Terms({'stool', '29', 'bar', 'griffin'})","Terms({'stool', 's', 'minimalist', 'feet', 'hi...",Kitchen & Dining Furniture,Terms({'furnitur'}),"Terms({'dine', 'kitchen', 'furnitur'})","Terms({'dine', 'furnitur', 'furniturekitchen'})"

## Query -> Full classification

Our usual list of classifications

**EXCEPT** - we're not passing them to the LLM, we're building an embedding index of them on this line

```
model = SentenceTransformer('all-MiniLM-L6-v2')
real_classifications = model.encode(classifications_list)
top_level_category_list = np.asarray([c.split(" / ")[0].strip() for c in classifications_list])
```

**Lookup** we also do a lookup in `classifications` to map a hallucinated classification to our real classifications

```
    @property
    def classifications(self):
        """Search with model to resolve to real classification."""
        actuals = []
        for halluc_class in self.hallucinated_classification:
            top_level_halluc_category = halluc_class.split(" / ")[0].strip()

            query_embedding = model.encode(halluc_class)
            dot_prods = np.dot(real_classifications, query_embedding)
            actual = classifications_list[np.argmax(dot_prods)]
            while actual in actuals:
                dot_prods[np.argmax(dot_prods)] = -1
                actual = classifications_list[np.argmax(dot_prods)]
```

In [19]:
import numpy as np

classifications_list = np.asarray([
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs',
 'Rugs / Area Rugs',
 'Furniture / Office Furniture / Desks',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / End & Side Tables',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows',
 'Furniture / Bedroom Furniture / Dressers & Chests',
 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities',
 'Furniture / Living Room Furniture / Console Tables',
 'Décor & Pillows / Art / All Wall Art',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs',
 'Furniture / Office Furniture / Office Chairs',
 'Décor & Pillows / Mirrors / All Mirrors',
 'Bed & Bath / Bedding / All Bedding',
 'Décor & Pillows / Wall Décor / Wall Accents',
 'Furniture / Living Room Furniture / Chairs & Seating / Recliners',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen and Dining Sets',
 'Décor & Pillows / Window Treatments / Curtains & Drapes',
 'Furniture / Living Room Furniture / Sectionals',
 'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers',
 'Lighting / Ceiling Lights / Chandeliers',
 'Furniture / Bedroom Furniture / Nightstands',
 'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Desks',
 'Décor & Pillows / Home Accessories / Decorative Objects',
 'Furniture / Bedroom Furniture / Beds & Headboards / Headboards',
 'Furniture / Living Room Furniture / Sofas',
 'Furniture / Living Room Furniture / Cabinets & Chests',
 'Décor & Pillows / Clocks / Wall Clocks',
 'Storage & Organization / Bathroom Storage & Organization / Bathroom Cabinets & Shelving',
 'Lighting / Table & Floor Lamps / Table Lamps',
 'Furniture / Living Room Furniture / Ottomans & Poufs',
 'Furniture / Kitchen & Dining Furniture / Kitchen Islands & Carts',
 'Furniture / Living Room Furniture / Bookcases',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals',
 'Furniture / Office Furniture / Office Storage Cabinets',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables',
 'Contractor / Entry & Hallway / Coat Racks & Umbrella Stands',
 'Bed & Bath / Bedding Essentials / Mattress Pads & Toppers',
 'Home Improvement / Hardware / Home Hardware / Switch Plates',
 'Baby & Kids / Toddler & Kids Playroom / Playroom Furniture / Toddler & Kids Chairs & Seating',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Outdoor Covers / Patio Furniture Covers',
 'Rugs / Doormats',
 'Rugs / Kitchen Mats',
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Queen Size Beds',
 'Furniture / Bedroom Furniture / Daybeds',
 'Furniture / Living Room Furniture / Living Room Sets',
 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Single Hole Bathroom Sink Faucets',
 'Outdoor / Outdoor Décor / Statues & Sculptures',
 'Décor & Pillows / Art / All Wall Art / Green Wall Art',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Table Sets',
 'Furniture / Living Room Furniture / Chairs & Seating / Chaise Lounge Chairs',
 'Storage & Organization / Wall Shelving & Organization / Wall and Display Shelves',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Rectangle Coffee Tables',
 'Décor & Pillows / Art / All Wall Art / Brown Wall Art',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools / Counter (24-27) Bar Stools & Counter Stools',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Plant Stands & Tables',
 'Décor & Pillows / Window Treatments / Curtain Hardware & Accessories',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Chairs / Side Kitchen & Dining Chairs',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs',
 'Furniture / Living Room Furniture / Chairs & Seating / Benches',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks / Farmhouse & Apron Kitchen Sinks',
 'Kitchen & Tabletop / Kitchen Organization / Food Pantries',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks / Black Towel & Robe Hooks',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Deck Boxes & Patio Storage',
 'Outdoor / Garden / Planters',
 'Lighting / Wall Lights / Bathroom Vanity Lighting',
 'Furniture / Kitchen & Dining Furniture / Sideboards & Buffets',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Storage Racks & Shelving Units',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Bronze Cabinet & Drawer Pulls',
 'Storage & Organization / Storage Containers & Drawers / All Storage Containers',
 'Bed & Bath / Shower Curtains & Accessories / Shower Curtains & Shower Liners',
 'Storage & Organization / Bathroom Storage & Organization / Hampers & Laundry Baskets',
 'Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / LED Light Bulbs',
 'Décor & Pillows / Art / All Wall Art / Blue Wall Art',
 'Bed & Bath / Mattresses & Foundations / Innerspring Mattresses',
 'Lighting / Outdoor Lighting / Outdoor Wall Lighting',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Natural Material Storage / Log Storage',
 'Bed & Bath / Bathroom Accessories & Organization / Countertop Bath Accessories',
 'Storage & Organization / Shoe Storage / All Shoe Storage',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Ceramic Floor Tiles & Wall Tiles',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Black Cabinet & Drawer Pulls',
 'Bed & Bath / Mattresses & Foundations / Adjustable Beds',
 "Rugs / Area Rugs / 2' x 3' Area Rugs",
 'Commercial Business Furniture / Commercial Office Furniture / Office Storage & Filing / Office Carts & Stands / All Carts & Stands',
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Twin Beds',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Widespread Bathroom Sink Faucets',
 "Rugs / Area Rugs / 4' x 6' Area Rugs",
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets',
 'Kitchen & Tabletop / Tableware & Drinkware / Table & Kitchen Linens / All Table Linens',
 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Food Storage Containers',
 'Décor & Pillows / Flowers & Plants / Faux Flowers',
 'Bed & Bath / Bedding / All Bedding / Twin Bedding',
 'Furniture / Bedroom Furniture / Dressers & Chests / White Dressers & Chests',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Porcelain Floor Tiles & Wall Tiles',
 'Home Improvement / Flooring, Walls & Ceiling / Flooring Installation & Accessories / Molding & Millwork / Wall Molding & Millwork',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Barn Door Hardware',
 'Bed & Bath / Bedding / Sheets & Pillowcases',
 'Furniture / Office Furniture / Chair Mats / Hard Floor Chair Mats',
 'Outdoor / Outdoor Fencing & Flooring / All Fencing',
 'Storage & Organization / Closet Storage & Organization / Clothes Racks & Garment Racks',
 'Kitchen & Tabletop / Kitchen Utensils & Tools / Colanders, Strainers, & Salad Spinners',
 'Outdoor / Hot Tubs & Saunas / Saunas',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Blue Throw Pillows',
 'Bed & Bath / Bedding Essentials / Bed Pillows',
 'Lighting / Wall Lights / Wall Sconces',
 'Outdoor / Front Door Décor & Curb Appeal / Mailboxes',
 'Outdoor / Garden / Greenhouses',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Faucets & Systems',
 'Bed & Bath / Mattresses & Foundations / Queen Mattresses',
 'Furniture / Bedroom Furniture / Jewelry Armoires',
 'Outdoor / Outdoor Shades / Awnings',
 'Baby & Kids / Nursery Bedding / Crib Bedding Sets',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Knobs / Brass Cabinet & Drawer Knobs',
 'Décor & Pillows / Art / All Wall Art / Red Wall Art',
 'Lighting / Ceiling Lights / All Ceiling Lights',
 'Lighting / Light Bulbs & Hardware / Lighting Components',
 'Furniture / Game Tables & Game Room Furniture / Poker & Card Tables',
 'Appliances / Kitchen Appliances / Range Hoods / All Range Hoods',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Natural Stone Floor Tiles & Wall Tiles',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Bar Stools & Counter Stools / All Bar Stools & Counter Stools / Bar (28-33) Bar Stools & Counter Stools',
 'Outdoor / Outdoor Cooking & Tableware / Outdoor Serving & Tableware / Coolers, Baskets & Tubs / Picnic Baskets & Backpacks',
 'Décor & Pillows / Picture Frames & Albums / All Picture Frames',
 'Bed & Bath / Shower Curtains & Accessories / Shower Curtain Hooks',
 'Outdoor / Outdoor Shades / Outdoor Umbrellas / Patio Umbrella Stands & Bases',
 'Outdoor / Outdoor & Patio Furniture / Patio Bar Furniture / Patio Bar Stools',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Toilets & Bidets / Toilet Paper Holders / Free Standing Toilet Paper Holders',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Bike & Sport Racks',
 'Appliances / Kitchen Appliances / Refrigerators & Freezers / All Refrigerators / French Door Refrigerators',
 'Décor & Pillows / Home Accessories / Decorative Trays',
 'School Furniture and Supplies / School Spaces / Computer Lab Furniture / Podiums & Lecterns',
 'Lighting / Light Bulbs & Hardware / Lighting Shades',
 'Furniture / Kitchen & Dining Furniture / Bar Furniture / Home Bars & Bar Sets',
 'Lighting / Table & Floor Lamps / Floor Lamps',
 'Décor & Pillows / Wall Décor / Wall Accents / Brown Wall Accents',
 'Kitchen & Tabletop / Small Kitchen Appliances / Pressure & Slow Cookers / Slow Cookers / Slow Slow Cookers',
 'Décor & Pillows / Window Treatments / Curtains & Drapes / 90 Inch Curtains & Drapes',
 'Furniture / Bedroom Furniture / Armoires & Wardrobes',
 'Kitchen & Tabletop / Tableware & Drinkware / Flatware & Cutlery / Serving Utensils',
 'Baby & Kids / Baby & Kids Décor & Lighting / All Baby & Kids Wall Art',
 'Furniture / Office Furniture / Desks / Writing Desks',
 'Furniture / Office Furniture / Office Chairs / Task Office Chairs',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Shower & Bathtub Doors',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Rocking Chairs & Gliders',
 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Wall Paneling',
 'Outdoor / Garden / Plant Stands & Accessories',
 'Furniture / Kitchen & Dining Furniture / Dining Tables & Seating / Kitchen & Dining Tables / 4 Seat Kitchen & Dining Tables',
 'Décor & Pillows / Home Accessories / Vases, Urns, Jars & Bottles',
 'Lighting / Wall Lights / Under Cabinet Lighting / Strip Under Cabinet Lighting',
 'Furniture / Bedroom Furniture / Bedroom and Makeup Vanities',
 'Pet / Dog / Dog Bowls & Feeding Supplies / Pet Bowls & Feeders',
 'Décor & Pillows / Candles & Holders / Candle Holders',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Shower & Bathtub Accessories',
 'Furniture / Office Furniture / Office Chair Accessories / Seat Cushion Office Chair Accessories',
 'Furniture / Office Furniture / Chair Mats',
 'Furniture / Living Room Furniture / Chairs & Seating / Massage Chairs',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities / Modern & Contemporary Bathroom Vanities',
 'Lighting / Ceiling Fans / All Ceiling Fans',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Black Kitchen Faucets',
 'Lighting / Light Bulbs & Hardware / Light Bulbs / All Light Bulbs / Incandescent Light Bulbs',
 'Home Improvement / Flooring, Walls & Ceiling / Flooring Installation & Accessories / Molding & Millwork',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Bathtubs',
 'Décor & Pillows / Art / All Wall Art / Yellow Wall Art',
 'Pet / Dog / Pet Gates, Fences & Doors / Pet Gates',
 'Furniture / Bedroom Furniture / Beds & Headboards / Bed Frames / Twin Bed Frames',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel Bars, Racks, and Stands / Metal Towel Bars, Racks, and Stands',
 'Décor & Pillows / Art / All Wall Art / Pink Wall Art',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Smoke Detectors / Wall & Ceiling Mounted Smoke Detectors',
 'Outdoor / Garden / Planters / Plastic Planters',
 'Décor & Pillows / Mirrors / All Mirrors / Accent Mirrors',
 'Appliances / Kitchen Appliances / Range Hoods / All Range Hoods / Wall Mount Range Hoods',
 'Outdoor / Garden / Garden Décor / Lawn & Garden Accents',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Round Coffee Tables',
 'Kitchen & Tabletop / Tableware & Drinkware / Dinnerware / Dining Bowls',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Heads / Dual Shower Heads',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Glass Floor Tiles & Wall Tiles',
 'School Furniture and Supplies / Facilities & Maintenance / Trash & Recycling',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Nickel Cabinet & Drawer Pulls',
 'Storage & Organization / Closet Storage & Organization / Closet Systems',
 'Furniture / Bedroom Furniture / Beds & Headboards / Beds / Full & Double Beds',
 'Commercial Business Furniture / Commercial Office Furniture / Office Storage & Filing / Office Carts & Stands / All Carts & Stands / Printer Carts & Stands',
 'Storage & Organization / Closet Storage & Organization / Closet Accessories',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities / Traditional Bathroom Vanities',
 'Home Improvement / Plumbing / Core Plumbing / Parts & Components',
 'Holiday Décor / Christmas / Christmas Trees / All Christmas Trees',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Black Throw Pillows',
 'Furniture / Game Tables & Game Room Furniture / Sports Team Fan Shop & Memorabillia / Life Size Cutouts',
 'Lighting / Ceiling Lights / Pendant Lighting',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Towel Storage / Towel & Robe Hooks',
 'Appliances / Washers & Dryers / Dryers / All Dryers / Gas Dryers',
 'Outdoor / Outdoor Recreation / Backyard Play / Kids Cars & Ride-On Toys',
 'Kitchen & Tabletop / Small Kitchen Appliances / Coffee, Espresso, & Tea / Coffee Makers',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Heads',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals / Sectional Patio Sofas & Sectionals',
 'Lighting / Wall Lights / Under Cabinet Lighting',
 'Foodservice / Foodservice Tables / Table Parts',
 'Lighting / Outdoor Lighting / Landscape Lighting / All Landscape Lighting / Fence Post Cap Landscape Lighting',
 'Lighting / Outdoor Lighting / Landscape Lighting / All Landscape Lighting',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Tables / All Patio Tables',
 'Commercial Business Furniture / Commercial Office Furniture / Office Storage & Filing / Office Carts & Stands / All Carts & Stands / Utility Carts & Stands',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Outdoor Chaise & Lounge Chairs',
 'Furniture / Living Room Furniture / Chairs & Seating / Recliners / Brown Recliners',
 'Pet / Bird / Bird Perches & Play Gyms',
 'Décor & Pillows / Picture Frames & Albums / All Picture Frames / Single Picture Picture Frames',
 'Lighting / Outdoor Lighting / Outdoor Lanterns & Lamps',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls',
 'Bed Accessories',
 'Clips/Clamps',
 'Décor & Pillows / Wall Décor / Wall Decals',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles',
 'Bed & Bath / Bedding / Sheets & Pillowcases / Twin XL Sheets & Pillowcases',
 'Kitchen & Tabletop / Tableware & Drinkware / Serveware / Serving Trays & Boards / Serving Trays & Platters / Serving Serving Trays & Platters',
 'Holiday Décor / Holiday Lighting',
 'Décor & Pillows / Wall Décor / Memo Boards',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Toilets & Bidets / Toilet Paper Holders / Wall Mounted Toilet Paper Holders',
 'Décor & Pillows / Window Treatments / Curtains & Drapes / 63 Inch and Less Curtains & Drapes',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Door Knobs / Egg Door Knobs',
 'Décor & Pillows / Clocks / Wall Clocks / Analog Wall Clocks',
 'Home Improvement / Doors & Door Hardware / Interior Doors / Sliding Interior Doors',
 'Outdoor / Outdoor Recreation / Outdoor Games / All Outdoor Games',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Door Levers / Round Door Levers',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Sheds / Storage Sheds',
 'Home Improvement / Doors & Door Hardware / Door Hardware & Accessories / Door Levers',
 'School Furniture and Supplies / School Furniture / School Tables / Folding Tables / Wood Folding Tables',
 'Décor & Pillows / Wall Décor / Wall Accents / Green Wall Accents',
 'School Furniture and Supplies / Facilities & Maintenance / Commercial Signage',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Garage Storage Cabinets',
 'Furniture / Bedroom Furniture / Dressers & Chests / Beige Dressers & Chests',
 'Storage & Organization / Wall Shelving & Organization / Wall & Display Shelves',
 'Furniture / Game Tables & Game Room Furniture / Dartboards & Cabinets',
 'Outdoor / Outdoor Décor / Outdoor Pillows & Cushions / Patio Furniture Cushions / Lounge Chair Patio Furniture Cushions',
 'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Dining Sets / Two Person Patio Dining Sets',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / Ivory & Cream Throw Pillows',
 'Appliances / Washers & Dryers / Washer & Dryer Sets / Black Washer & Dryer Sets',
 'School Furniture and Supplies / School Furniture / School Chairs & Seating / Stackable Chairs',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Pulls / Brass Cabinet & Drawer Pulls',
 'School Furniture and Supplies / School Boards & Technology / AV, Mounts & Tech Accessories / Electronic Mounts & Stands / Computer Mounts',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Papasan Accent Chairs',
 'Storage & Organization / Shoe Storage / All Shoe Storage / Rack Shoe Storage',
 'Storage & Organization / Shoe Storage / All Shoe Storage / Cabinet Shoe Storage',
 'Storage & Organization / Storage Containers & Drawers / Storage Drawers',
 'Appliances / Kitchen Appliances / Wine & Beverage Coolers / Water Coolers',
 'Furniture / Living Room Furniture / Chairs & Seating / Rocking Chairs',
 'Kitchen & Tabletop / Tableware & Drinkware / Serveware / Serving Bowls & Baskets / Serving Bowls / NA Serving Bowls',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / Projection Screens / Inflatable Projection Screens',
 'Appliances / Kitchen Appliances / Large Appliance Parts & Accessories',
 'Storage & Organization / Bathroom Storage & Organization / Hampers & Laundry Baskets / Laundry Hampers & Laundry Baskets',
 'Furniture / Office Furniture / Office Stools',
 'Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Outdoor Club Chairs / Metal Outdoor Club Chairs',
 'School Furniture and Supplies / School Furniture / School Tables / Folding Tables',
 'Lighting / Wall Lights / Bathroom Vanity Lighting / Traditional Bathroom Vanity Lighting',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Sinks & Faucet Components / Bathroom Sink Faucets / Centerset Bathroom Sink Faucets',
 'Décor & Pillows / Flowers & Plants / Faux Flowers / Orchid Faux Flowers',
 'Home Improvement / Flooring, Walls & Ceiling / Floor Tiles & Wall Tiles / Metal Floor Tiles & Wall Tiles',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Sinks',
 'Storage & Organization / Garage & Outdoor Storage & Organization / Outdoor Covers / Grill Covers / Charcoal Grill Grill Covers',
 'Outdoor / Outdoor Décor / Outdoor Wall Décor',
 'Storage & Organization / Cleaning & Laundry Organization / Laundry Room Organizers',
 'Reception Area / Reception Seating / Reception Sofas & Loveseats',
 'Kitchen & Tabletop / Cookware & Bakeware / Baking Sheets & Pans / Bread & Loaf Pans / Steel Bread & Loaf Pans',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Wingback Accent Chairs',
 'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Showers & Bathtubs / Showers & Bathtubs Plumbing / Shower Heads / Fixed Shower Heads',
 'Kitchen & Tabletop / Kitchen Utensils & Tools / Kitchen Gadgets / Pasta Makers & Accessories',
 'School Furniture and Supplies / School Furniture / School Chairs & Seating / Classroom Chairs / High School & College Classroom Chairs',
 'Furniture / Living Room Furniture / Sectionals / Stationary Sectionals',
 'Furniture / Kitchen & Dining Furniture / Sideboards & Buffets / Drawer Equipped Sideboards & Buffets',
 'Kitchen & Tabletop / Cookware & Bakeware / Baking Sheets & Pans / Bread & Loaf Pans',
 'Kitchen & Tabletop / Kitchen Utensils & Tools / Cooking Utensils / All Cooking Utensils / Kitchen Cooking Utensils',
 'Décor & Pillows / Flowers & Plants / Live Plants',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / Projection Screens / Folding Frame Projection Screens',
 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Metal Kitchen Canisters & Jars',
 'Outdoor / Outdoor Décor / Outdoor Fountains',
 'Outdoor / Outdoor Shades / Pergolas / Wood Pergolas',
 'Décor & Pillows / Candles & Holders / Candle Holders / Sconce Candle Holders',
 'Kitchen & Tabletop / Tableware & Drinkware / Serveware / Cake & Tiered Stands',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Chrome Kitchen Faucets',
 'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows / White Throw Pillows',
 'Outdoor / Outdoor Fencing & Flooring / Turf',
 'Décor & Pillows / Window Treatments / Valances & Kitchen Curtains',
 'Home Improvement / Hardware / Cabinet Hardware / Cabinet & Drawer Knobs / Black Cabinet & Drawer Knobs',
 'Home Improvement / Kitchen Remodel & Kitchen Fixtures / Kitchen Sinks & Faucet Components / Kitchen Faucets / Bronze Kitchen Faucets',
 'Appliances / Washers & Dryers / Washer & Dryer Sets',
 'Décor & Pillows / Clocks / Mantel & Tabletop Clocks',
 'Home Improvement / Doors & Door Hardware / Interior Doors',
 'Storage & Organization / Wall Shelving & Organization / Wall & Display Shelves / Floating Wall & Display Shelves',
 'Outdoor / Outdoor Recreation / Backyard Play / Climbing Toys & Slides',
 'Home Improvement / Building Equipment / Dollies / Hand Truck Dollies',
 'Baby & Kids / Toddler & Kids Bedroom Furniture / Baby & Kids Dressers',
 'Décor & Pillows / Mirrors / All Mirrors / Leaning & Floor Mirrors',
 'Kitchen & Tabletop / Tableware & Drinkware / Drinkware / Mugs & Teacups',
 'Décor & Pillows / Flowers & Plants / Wreaths',
 'Outdoor / Outdoor Shades / Pergolas / Metal Pergolas',
 'Bed & Bath / Bedding / Sheets & Pillowcases / Twin Sheets & Pillowcases',
 'Outdoor / Outdoor Shades / Pergolas',
 'Reception Area / Reception Seating / Office Sofas & Loveseats',
 'Décor & Pillows / Home Accessories / Indoor Fountains',
 'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters / Kitchen Canisters & Jars / Ceramic Kitchen Canisters & Jars',
 'Décor & Pillows / Window Treatments / Curtain Hardware & Accessories / Bracket Curtain Hardware & Accessories',
 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Accent Tiles / Ceramic Accent Tiles',
 'Home Improvement / Flooring, Walls & Ceiling / Walls & Ceilings / Accent Tiles',
 'Furniture / Living Room Furniture / Chairs & Seating / Accent Chairs / Arm Accent Chairs',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Free Form Coffee Tables',
 'Décor & Pillows / Flowers & Plants / Faux Flowers / Rose Faux Flowers',
 'Bed & Bath / Mattresses & Foundations / Innerspring Mattresses / Twin Innerspring Mattresses',
 'Outdoor / Outdoor Décor / Outdoor Pillows & Cushions / Patio Furniture Cushions / Dining Chair Patio Furniture Cushions',
 'Furniture / Living Room Furniture / TV Stands & Media Storage Furniture / TV Stands & Entertainment Centers / Traditional TV Stands & Entertainment Centers',
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Plant Stands & Tables / Square Plant Stands & Tables',
 'Storage & Organization / Wall Shelving & Organization / Wall & Display Shelves / Corner Wall & Display Shelves',
 "Rugs / Area Rugs / 3' x 5' Area Rugs",
 'Kitchen & Tabletop / Tableware & Drinkware / Drinkware / Mugs & Teacups / Coffee Mugs & Teacups',
 'Contractor / Entry & Hallway / Coat Racks & Umbrella Stands / Wall Mounted Coat Racks & Umbrella Stands',
 "Baby & Kids / Toddler & Kids Playroom / Indoor Play / Kids' Playhouses",
 'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables / Square Coffee Tables',
 'Baby & Kids / Toddler & Kids Playroom / Indoor Play / Dollhouses & Accessories',
 'Bed & Bath / Bedding / All Bedding / Queen Bedding',
])

from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')
real_classifications = model.encode(classifications_list)
top_level_category_list = np.asarray([c.split(CAT_SEP)[0].strip() for c in classifications_list])
top_level_category_list

array(['Furniture', 'Furniture', 'Rugs', 'Furniture', 'Furniture',
       'Furniture', 'Décor & Pillows', 'Furniture', 'Outdoor',
       'Home Improvement', 'Furniture', 'Décor & Pillows', 'Furniture',
       'Furniture', 'Furniture', 'Décor & Pillows', 'Bed & Bath',
       'Décor & Pillows', 'Furniture', 'Furniture', 'Décor & Pillows',
       'Furniture', 'Baby & Kids', 'Furniture', 'Lighting', 'Furniture',
       'Baby & Kids', 'Décor & Pillows', 'Furniture', 'Furniture',
       'Furniture', 'Décor & Pillows', 'Storage & Organization',
       'Lighting', 'Furniture', 'Furniture', 'Furniture', 'Outdoor',
       'Furniture', 'Furniture', 'Contractor', 'Bed & Bath',
       'Home Improvement', 'Baby & Kids', 'Storage & Organization',
       'Rugs', 'Rugs', 'Furniture', 'Furniture', 'Furniture', 'Outdoor',
       'Home Improvement', 'Outdoor', 'Décor & Pillows', 'Furniture',
       'Furniture', 'Storage & Organization', 'Furniture',
       'Décor & Pillows', 'Furniture', 'Furniture', 'Décor & Pillows',
       'Furniture', 'Outdoor', 'Furniture', 'Home Improvement',
       'Kitchen & Tabletop', 'Home Improvement', 'Storage & Organization',
       'Outdoor', 'Lighting', 'Furniture', 'Storage & Organization',
       'Home Improvement', 'Storage & Organization', 'Bed & Bath',
       'Storage & Organization', 'Lighting', 'Décor & Pillows',
       'Bed & Bath', 'Lighting', 'Storage & Organization', 'Bed & Bath',
       'Storage & Organization', 'Home Improvement', 'Home Improvement',
       'Bed & Bath', 'Rugs', 'Commercial Business Furniture', 'Furniture',
       'Home Improvement', 'Rugs', 'Home Improvement',
       'Kitchen & Tabletop', 'Kitchen & Tabletop', 'Décor & Pillows',
       'Bed & Bath', 'Furniture', 'Home Improvement', 'Home Improvement',
       'Home Improvement', 'Bed & Bath', 'Furniture', 'Outdoor',
       'Storage & Organization', 'Kitchen & Tabletop', 'Outdoor',
       'Décor & Pillows', 'Bed & Bath', 'Lighting', 'Outdoor', 'Outdoor',
       'Home Improvement', 'Bed & Bath', 'Furniture', 'Outdoor',
       'Baby & Kids', 'Home Improvement', 'Décor & Pillows', 'Lighting',
       'Lighting', 'Furniture', 'Appliances', 'Home Improvement',
       'Furniture', 'Outdoor', 'Décor & Pillows', 'Bed & Bath', 'Outdoor',
       'Outdoor', 'Home Improvement', 'Storage & Organization',
       'Appliances', 'Décor & Pillows', 'School Furniture and Supplies',
       'Lighting', 'Furniture', 'Lighting', 'Décor & Pillows',
       'Kitchen & Tabletop', 'Décor & Pillows', 'Furniture',
       'Kitchen & Tabletop', 'Baby & Kids', 'Furniture', 'Furniture',
       'Home Improvement', 'Outdoor', 'Home Improvement', 'Outdoor',
       'Furniture', 'Décor & Pillows', 'Lighting', 'Furniture', 'Pet',
       'Décor & Pillows', 'Home Improvement', 'Furniture', 'Furniture',
       'Furniture', 'Home Improvement', 'Lighting', 'Home Improvement',
       'Lighting', 'Home Improvement', 'Home Improvement',
       'Décor & Pillows', 'Pet', 'Furniture', 'Home Improvement',
       'Décor & Pillows', 'Home Improvement', 'Outdoor',
       'Décor & Pillows', 'Appliances', 'Outdoor', 'Furniture',
       'Kitchen & Tabletop', 'Home Improvement', 'Home Improvement',
       'School Furniture and Supplies', 'Home Improvement',
       'Storage & Organization', 'Furniture',
       'Commercial Business Furniture', 'Storage & Organization',
       'Home Improvement', 'Home Improvement', 'Holiday Décor',
       'Décor & Pillows', 'Furniture', 'Lighting', 'Home Improvement',
       'Appliances', 'Outdoor', 'Kitchen & Tabletop', 'Home Improvement',
       'Outdoor', 'Lighting', 'Foodservice', 'Lighting', 'Lighting',
       'Outdoor', 'Commercial Business Furniture', 'Outdoor', 'Furniture',
       'Pet', 'Décor & Pillows', 'Lighting', 'Home Improvement',
       'Bed Accessories', 'Clips', 'Décor & Pillows', 'Home Improvement',
       'Bed & Bath', 'Kitchen & Tabletop', 'Holiday Décor',
       'Décor & Pillows', 'Home Improvement', 'Décor & Pillows',
       'Home Improvement', 'Décor & Pillows', 'Home Improvement',
       'Outdoor', 'Home Improvement', 'Storage & Organization',
       'Home Improvement', 'School Furniture and Supplies',
       'Décor & Pillows', 'School Furniture and Supplies',
       'Storage & Organization', 'Furniture', 'Storage & Organization',
       'Furniture', 'Outdoor', 'Outdoor', 'Décor & Pillows', 'Appliances',
       'School Furniture and Supplies', 'Home Improvement',
       'School Furniture and Supplies', 'Furniture',
       'Storage & Organization', 'Storage & Organization',
       'Storage & Organization', 'Appliances', 'Furniture',
       'Kitchen & Tabletop', 'Furniture', 'Appliances',
       'Storage & Organization', 'Furniture', 'Outdoor',
       'School Furniture and Supplies', 'Lighting', 'Home Improvement',
       'Décor & Pillows', 'Home Improvement', 'Home Improvement',
       'Storage & Organization', 'Outdoor', 'Storage & Organization',
       'Reception Area', 'Kitchen & Tabletop', 'Furniture',
       'Home Improvement', 'Kitchen & Tabletop',
       'School Furniture and Supplies', 'Furniture', 'Furniture',
       'Kitchen & Tabletop', 'Kitchen & Tabletop', 'Décor & Pillows',
       'Furniture', 'Kitchen & Tabletop', 'Outdoor', 'Outdoor',
       'Décor & Pillows', 'Kitchen & Tabletop', 'Home Improvement',
       'Décor & Pillows', 'Outdoor', 'Décor & Pillows',
       'Home Improvement', 'Home Improvement', 'Appliances',
       'Décor & Pillows', 'Home Improvement', 'Storage & Organization',
       'Outdoor', 'Home Improvement', 'Baby & Kids', 'Décor & Pillows',
       'Kitchen & Tabletop', 'Décor & Pillows', 'Outdoor', 'Bed & Bath',
       'Outdoor', 'Reception Area', 'Décor & Pillows',
       'Kitchen & Tabletop', 'Décor & Pillows', 'Home Improvement',
       'Home Improvement', 'Furniture', 'Furniture', 'Décor & Pillows',
       'Bed & Bath', 'Outdoor', 'Furniture', 'Furniture',
       'Storage & Organization', 'Rugs', 'Kitchen & Tabletop',
       'Contractor', 'Baby & Kids', 'Furniture', 'Baby & Kids',
       'Bed & Bath'], dtype='<U29')

### Structured types

* Returns a `hallucinated_classification` that we turn into a real classification via finding the most similar embedding

In [20]:
from pydantic import BaseModel, Field
from typing import List, Literal
from cheat_at_search.enrich import AutoEnricher
import numpy as np

known_categories = set([c.split(CAT_SEP)[0].strip() for c in classifications_list])
known_sub_categories = set([c.split(CAT_SEP)[1].strip() for c in classifications_list if len(c.split(CAT_SEP)) > 1])

known_sub_categories


class Query(BaseModel):
    """
    Base model for search queries, containing common query attributes.
    """
    keywords: str = Field(
        ...,
        description="The original search query keywords sent in as input"
    )


CAT_SEP = '/'


class QueryClassification(Query):
    """
    Represents a classification of a product.

    In this case, hallucinated, something the model is making up that looks like one
    of our classifications
    """
    hallucinated_classification: List[str] = Field(
        description="The classification you created for the query."
    )

    @property
    def classifications(self):
        """Search with model to resolve to real classification."""
        actuals = []
        for halluc_class in self.hallucinated_classification:
            query_embedding = model.encode(halluc_class)
            dot_prods = np.dot(real_classifications, query_embedding)
            actual = classifications_list[np.argmax(dot_prods)]
            while actual in actuals:
                dot_prods[np.argmax(dot_prods)] = -1
                actual = classifications_list[np.argmax(dot_prods)]

            actuals.append(actual)
        return actuals

    @property
    def categories(self):
        resolved_classification = self.classifications
        if len(resolved_classification) == 0 or resolved_classification == ["No Classification Fits"]:
            return []
        cats = []
        for c in resolved_classification:
            cats.append(c.split(CAT_SEP)[0].strip())
        return set(cats)

    @property
    def sub_categories(self):
        resolved_classification = self.classifications
        if len(resolved_classification) == 0 or resolved_classification == ["No Classification Fits"]:
            return []

        cats = []
        for c in resolved_classification:
            c_split = c.split(CAT_SEP)
            if len(c_split) < 2:
                continue
            cats.append(c.split(CAT_SEP)[1].strip())
        return set(cats)

    @property
    def cat_subcat(self):
        resolved_classification = self.classifications
        if len(resolved_classification) == 0 or resolved_classification == ["No Classification Fits"]:
            return []
        cat_subcats = []
        for c in resolved_classification:
            c_split = c.split(CAT_SEP)
            if len(c_split) < 2:
                continue
            cat_subcats.append(f"{c_split[0].strip()} / {c_split[1].strip()}")
        return set(cat_subcats)

### Query classification code

Notice our prompt:
1. Is given some examples of what classifications might look like
2. Asked to "be creative" to give us a diverse set of top level categories

In [21]:
enricher = AutoEnricher(
     model="openai/gpt-4.1-nano",
     system_prompt="Your task is to create novel, never seen before, furniture, home goods, or hardware classification that best fit a search query. ",
     response_model=QueryClassification
)

def get_prompt_fully_qualified(query):
        prompt = f"""

        Some inspiration on what these look like is at the bottom.

        Here is the users request:

        {query}

        Product classifications might look like:

        'Furniture / Living Room Furniture / Coffee Tables & End Tables / Coffee Tables'
        'Décor & Pillows / Decorative Pillows & Blankets / Throw Pillows'
        'Furniture / Bedroom Furniture / Dressers & Chests'
        'Outdoor / Outdoor & Patio Furniture / Patio Furniture Sets / Patio Conversation Sets'
        'Home Improvement / Bathroom Remodel & Bathroom Fixtures / Bathroom Vanities / All Bathroom Vanities'
        'Lighting / Wall Lights / Bathroom Vanity Lighting'
        'Kitchen & Tabletop / Kitchen Organization / Food Storage & Canisters'
        'School Furniture and Supplies / School Furniture / School Chairs & Seating / Stackable Chairs',
        'Baby & Kids / Toddler & Kids Bedroom Furniture / Kids Beds',

        If you feel inspired, return many unique values in a list. Be creative. Cast a wide net with related but diverse categories.

        Return empty list if no clear classification could be inferred, the query is not clearly a furniture query

        """

        return prompt

def fully_classified(query):
    prompt = get_prompt_fully_qualified(query)
    return enricher.enrich(prompt)


def get_num_tokens(query):
    prompt = get_prompt_fully_qualified(query)
    return enricher.get_num_tokens(prompt)

fully_classified("dinosaur"), fully_classified("sofa loveseat"), fully_classified("sofa loveseat").classifications

(QueryClassification(keywords='dinosaur', hallucinated_classification=['Decor & Wall Art / Themed Wall Decor / Dinosaur Wall Art', 'Kids & Baby Furniture / Kids Bedroom Decor / Dinosaur Themed Bedding & Accessories', 'Toys & Games / Dinosaur Toys / Dinosaur Action Figures and Collectibles', 'Outdoor & Garden / Dinosaur Garden Statues / Dinosaur Garden Decor', 'Party Supplies / Dinosaur Party Decorations / Dinosaur Themed Party Supplies', 'Educational Materials / Dinosaur Learning Kits / Dinosaur Fossil Excavation Sets']),
 QueryClassification(keywords='sofa loveseat', hallucinated_classification=['Furniture / Living Room Furniture / Sofas & Loveseats', 'Furniture / Modular & Sectional Sofas', 'Furniture / Convertible Sofas & Sleeper Sofas', 'Furniture / Customizable Sofas & Loveseats', 'Furniture / Vintage & Retro Sofas', 'Furniture / Eco-Friendly & Sustainable Sofas', 'Furniture / Luxury & Designer Sofas', 'Furniture / Small Space & Apartment Sofas']),
 [np.str_('Furniture / Living Room Furniture / Sofas'),
  np.str_('Furniture / Living Room Furniture / Sectionals'),
  np.str_('Furniture / Bedroom Furniture / Daybeds'),
  np.str_('Reception Area / Reception Seating / Office Sofas & Loveseats'),
  np.str_('Furniture / Living Room Furniture / Ottomans & Poufs'),
  np.str_('Outdoor / Outdoor & Patio Furniture / Outdoor Seating & Patio Chairs / Patio Seating / Patio Sofas & Sectionals'),
  np.str_('Furniture / Bedroom Furniture / Armoires & Wardrobes'),
  np.str_('Furniture / Bedroom Furniture / Nightstands')])

### Much lower number of tokens

We are using a cheaper model, and also we observe many fewer tokens

In [22]:
get_num_tokens("sofa loveseat")

(380, 90)

### Run an example

Notice how the hallucinated classifications look very specific, but then look at how they are resolved.

**Consider** What problems exist here? Or might creep up?

In [23]:
fully_classified("barnyard style doors").hallucinated_classification

['Home Improvement / Doors & Windows / Barn Doors & Sliding Doors / Barnyard Style Doors',
 'Furniture / Entryway Furniture / Barnyard Style Doors',
 'Decor / Wall Decor / Barnyard Themed Wall Art & Decor',
 'Outdoor / Garden & Yard Structures / Barnyard Style Garden Gates']

In [24]:
fully_classified("barnyard style doors").classifications

[np.str_('Home Improvement / Doors & Door Hardware / Interior Doors / Sliding Interior Doors'),
 np.str_('Home Improvement / Doors & Door Hardware / Interior Doors'),
 np.str_('Décor & Pillows / Art / All Wall Art'),
 np.str_('Pet / Dog / Pet Gates, Fences & Doors / Pet Gates')]

In [25]:
fully_classified("barnyard style doors").cat_subcat

{'Décor & Pillows / Art',
 'Home Improvement / Doors & Door Hardware',
 'Pet / Dog'}

### Redefine ground truth *for list use cases*

We defined a ground truth to look at jaccard + recall for specific categories

In [26]:
from cheat_at_search.wands_data import labeled_query_products, queries

def get_top_categories(column, no_fit_label, cutoff=0.8):
    # Get relevant products per query
    top_products = labeled_query_products[labeled_query_products['grade'] == 2]

    # Aggregate top categories
    categories_per_query_ideal = top_products.groupby('query')[column].value_counts().reset_index()

    # Get as percentage of all categories for this query
    top_cat_proportion = categories_per_query_ideal.groupby(['query', column]).sum() / categories_per_query_ideal.groupby('query').sum()
    top_cat_proportion = top_cat_proportion.drop(columns=column).reset_index()

    # Only look at cases where the category is > 0.8
    top_cat_proportion = top_cat_proportion[top_cat_proportion['count'] > cutoff]
    top_cat_proportion[column].fillna(no_fit_label, inplace=True)
    ground_truth_cat = top_cat_proportion
    # Give No Category Fits to all others without dominant category
    ground_truth_cat = ground_truth_cat.merge(queries, how='right', on='query')[['query', column, 'count']]
    ground_truth_cat[column].fillna(no_fit_label, inplace=True)
    return ground_truth_cat

# The original ground truth by category
ground_truth_cat = get_top_categories('category', 'No Category Fits', cutoff=0.8)


ground_truth_cat_list = get_top_categories('category', 'No Category Fits', cutoff=0.05)

# Group by query, collect category into list
ground_truth_cat_list = ground_truth_cat_list.groupby('query').agg({'category': list}).reset_index()
# Remove empty items on "No Category Fits" from lists
ground_truth_cat_list['category'] = ground_truth_cat_list['category'].apply(lambda x: [y.strip() for y in x if y and y != 'No Category Fits'])
ground_truth_cat_list

/tmp/ipykernel_36998/2868813019.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  top_cat_proportion[column].fillna(no_fit_label, inplace=True)
/tmp/ipykernel_36998/2868813019.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ground_truth_cat[column].fillna(no_fit_label, inplace=True)
/tmp/ipykernel_36998/2868813019.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  top_cat_proportion[column].fillna(no_fit_label, inplace=True)
/tmp/ipykernel_36998/2868813019.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ground_truth_cat[column].fillna(no_fit_label, inplace=True)

,query,category
0,12v dirt bike,[]
1,3 1/2 inch drawer pull,[Home Improvement]
2,3 piece rug set with runners,[Rugs]
3,3/4 size mattress,[]
4,30 inch bathroom vanity,[Home Improvement]
...,...,...
475,wrought tv stand,[Furniture]
476,zachary 72.5,[Furniture]
477,zakariyah twin platform,[Baby & Kids]
478,zen,"[Décor & Pillows, Home Improvement, Outdoor]"
479,zodiac pillow,[Décor & Pillows]

## Run Category search strategy with classifier

Identical to previous runs with a classifier of query -> list of classifications. We ask for the `categories` (which behind the scenes does teh embedding lookup). We then go through our usual boosting dance:

1. BM25 search
2. Boost category / subcategory matches

**Something to try (easy)** - change away from the MiniLM model and see if anything changes

**Something to try (advanced)** - What if we embedded the classification directly in the index, and searched that with the hallucinated classification?

In [28]:
from searcharray import SearchArray
from cheat_at_search.tokenizers import snowball_tokenizer
from cheat_at_search.strategy.strategy import SearchStrategy
import numpy as np


class CategorySearch(SearchStrategy):
    def __init__(self, products, query_to_cat,
                 name_boost=9.3,
                 description_boost=4.1,
                 category_boost=10,
                 sub_category_boost=5,
                 cat_subcat_boost=10):
        super().__init__(products)
        self.index = products
        self.index['product_name_snowball'] = SearchArray.index(
            products['product_name'], snowball_tokenizer)
        self.index['product_description_snowball'] = SearchArray.index(
            products['product_description'], snowball_tokenizer)

        cat_split = products['category hierarchy'].fillna('').str.split("/")

        products['category'] = cat_split.apply(
            lambda x: x[0].strip() if len(x) > 0 else ""
        )
        products['subcategory'] = cat_split.apply(
            lambda x: x[1].strip() if len(x) > 1 else ""
        )
        self.index['category_snowball'] = SearchArray.index(
            products['category'], snowball_tokenizer
        )
        self.index['subcategory_snowball'] = SearchArray.index(
            products['subcategory'], snowball_tokenizer
        )

        self.index['cat_subcat'] = products['category'] + products['subcategory']
        self.index['cat_subcat'] = self.index['cat_subcat'].fillna('')
        self.index['cat_subcat_snowball'] = SearchArray.index(
            self.index['cat_subcat'], snowball_tokenizer
        )

        self.query_to_cat = query_to_cat
        self.name_boost = name_boost
        self.description_boost = description_boost
        self.category_boost = category_boost
        self.sub_category_boost = sub_category_boost
        self.cat_subcat_boost = cat_subcat_boost

    def search(self, query, k=10):
        """Dumb baseline lexical search, but add a constant boost when
           the desired category or subcategory"""
        bm25_scores = np.zeros(len(self.index))
        structured = self.query_to_cat(query)
        tokenized = snowball_tokenizer(query)
        
        # ****
        # Baseline BM25 search from before
        for token in tokenized:
            bm25_scores += self.index['product_name_snowball'].array.score(token) * self.name_boost
            bm25_scores += self.index['product_description_snowball'].array.score(
                token) * self.description_boost

        # ****
        # If there's a subcategory, boost that by a constant amount
        for sub_category in structured.sub_categories:
            tokenized_subcategory = snowball_tokenizer(sub_category)
            subcategory_match = np.zeros(len(self.index))
            if tokenized_subcategory:
                subcategory_match = self.index['subcategory_snowball'].array.score(tokenized_subcategory) > 0
            bm25_scores[subcategory_match] += self.sub_category_boost

        # ****
        # If there's a category, boost that by a constant amount
        for category in structured.categories:
            tokenized_category = snowball_tokenizer(category)
            category_match = np.zeros(len(self.index))
            if tokenized_category:
                category_match = self.index['category_snowball'].array.score(tokenized_category) > 0
            bm25_scores[category_match] += self.category_boost

        # ***
        # If they occur togethere, boost by a constant amount
        for cat_subcat in structured.cat_subcat:
            tokenized_cat_subcat = snowball_tokenizer(cat_subcat)
            cat_subcat_match = np.zeros(len(self.index))
            if tokenized_cat_subcat:
                cat_subcat_match = self.index['cat_subcat_snowball'].array.score(tokenized_cat_subcat) > 0
            bm25_scores[cat_subcat_match] += self.cat_subcat_boost

        top_k = np.argsort(-bm25_scores)[:k]
        scores = bm25_scores[top_k]

        return top_k, scores

categorized_search = CategorySearch(products, fully_classified)
categorized_search.search('medium clips')

2026-04-02 01:39:14,059 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-04-02 01:39:14,062 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-04-02 01:39:14,063 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-04-02 01:39:14,164 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-04-02 01:39:14,263 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-04-02 01:39:14,359 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-04-02 01:39:14,456 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-04-02 01:39:14,512 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-04-02 01:39:14,515 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-04-02 01:39:14,516 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-04-02 01:39:14,529 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-04-02 01:39:14,546 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-04-02 01:39:14,547 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-04-02 01:39:14,563 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-04-02 01:39:14,574 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-04-02 01:39:14,577 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-04-02 01:39:14,578 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-04-02 01:39:14,969 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-04-02 01:39:15,375 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-04-02 01:39:15,793 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-04-02 01:39:16,230 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-04-02 01:39:16,403 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-04-02 01:39:16,443 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-04-02 01:39:16,449 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-04-02 01:39:16,701 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-04-02 01:39:16,776 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-04-02 01:39:16,778 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-04-02 01:39:16,866 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-04-02 01:39:17,282 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-04-02 01:39:17,284 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-04-02 01:39:17,285 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-04-02 01:39:17,344 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-04-02 01:39:17,403 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-04-02 01:39:17,463 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-04-02 01:39:17,523 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-04-02 01:39:17,563 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-04-02 01:39:17,564 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-04-02 01:39:17,565 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-04-02 01:39:17,567 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-04-02 01:39:17,568 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-04-02 01:39:17,568 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-04-02 01:39:17,574 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-04-02 01:39:17,576 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-04-02 01:39:17,579 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-04-02 01:39:17,579 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-04-02 01:39:17,650 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-04-02 01:39:17,719 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-04-02 01:39:17,789 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-04-02 01:39:17,859 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-04-02 01:39:17,902 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-04-02 01:39:17,903 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-04-02 01:39:17,904 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-04-02 01:39:17,908 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-04-02 01:39:17,910 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-04-02 01:39:17,911 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-04-02 01:39:17,918 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

2026-04-02 01:39:17,923 - searcharray.indexing - INFO - Indexing begins w/ 4 workers

INFO:searcharray.indexing:Indexing begins w/ 4 workers

2026-04-02 01:39:17,926 - searcharray.indexing - INFO - 0 Batch Start tokenization

INFO:searcharray.indexing:0 Batch Start tokenization

2026-04-02 01:39:17,926 - searcharray.indexing - INFO - Tokenizing 42994 documents

INFO:searcharray.indexing:Tokenizing 42994 documents

2026-04-02 01:39:17,997 - searcharray.indexing - INFO - Tokenized 10000 (23.259059403637718%)

INFO:searcharray.indexing:Tokenized 10000 (23.259059403637718%)

2026-04-02 01:39:18,071 - searcharray.indexing - INFO - Tokenized 20000 (46.518118807275435%)

INFO:searcharray.indexing:Tokenized 20000 (46.518118807275435%)

2026-04-02 01:39:18,145 - searcharray.indexing - INFO - Tokenized 30000 (69.77717821091315%)

INFO:searcharray.indexing:Tokenized 30000 (69.77717821091315%)

2026-04-02 01:39:18,216 - searcharray.indexing - INFO - Tokenized 40000 (93.03623761455087%)

INFO:searcharray.indexing:Tokenized 40000 (93.03623761455087%)

2026-04-02 01:39:18,259 - searcharray.indexing - INFO - Tokenization -- vstacking

INFO:searcharray.indexing:Tokenization -- vstacking

2026-04-02 01:39:18,260 - searcharray.indexing - INFO - Tokenization -- DONE

INFO:searcharray.indexing:Tokenization -- DONE

2026-04-02 01:39:18,261 - searcharray.indexing - INFO - Inverting docs->terms

INFO:searcharray.indexing:Inverting docs->terms

2026-04-02 01:39:18,265 - searcharray.indexing - INFO - Encoding positions to bit array

INFO:searcharray.indexing:Encoding positions to bit array

2026-04-02 01:39:18,267 - searcharray.indexing - INFO - Batch tokenization complete

INFO:searcharray.indexing:Batch tokenization complete

2026-04-02 01:39:18,267 - searcharray.indexing - INFO - (main thread) Processing 1 batch results

INFO:searcharray.indexing:(main thread) Processing 1 batch results

2026-04-02 01:39:18,275 - searcharray.indexing - INFO - Indexing from tokenization complete

INFO:searcharray.indexing:Indexing from tokenization complete

(array([36813, 37397, 34050, 36809, 37396, 27888, 37398, 27886, 36810,
         7262]),
 array([85.35794735, 84.99754143, 68.97158527, 68.62535572, 67.39479828,
        66.84630394, 66.0164814 , 65.3701973 , 64.83574677, 64.57731247]))

In [29]:
# categorized_search.sub_category_boost = 0
# categorized_search.category_boost = 0
# categorized_search.cat_subcat_boost = 0
top_k, scores = categorized_search.search('medium clips')
matched_products = products.iloc[top_k].copy()
matched_products['score'] = scores


matched_products[['product_name', 'category hierarchy', 'score']]

,product_name,category hierarchy,score
36813,"gem paper clips , plastic , medium size , 500/box",Clips/Clamps,85.357947
37397,"medium binder clips , 24/pack",Clips/Clamps,84.997541
34050,monett 10 piece medium clip set,NaN,68.971585
36809,"medium binder clips , steel wire , 5/8 '' capa...",Clips/Clamps,68.625356
37396,"paper clips , coated , jumbo , 80 clips per pa...",Clips/Clamps,67.394798
27888,fitting clips,Storage & Organization / Closet Storage & Orga...,66.846304
37398,"binder clips , medium,1-1/4 '' wide,5/8 '' cap...",Clips/Clamps,66.016481
27886,fretwell plastic hangers with clips for skirt/...,Storage & Organization / Closet Storage & Orga...,65.370197
36810,"regal clips , 100/box",Clips/Clamps,64.835747
7262,standard clips,"Home Improvement / Flooring, Walls & Ceiling /...",64.577312

In [30]:
graded_fully_classified = run_strategy(categorized_search, judgments)
graded_fully_classified

Searching: 100%|██████████| 480/480 [02:37<00:00,  3.05it/s]

,product_id,product_name,product_class,category hierarchy,product_description,product_features,rating_count,average_rating,review_count,features,...,score,query,query_id,rank,grade,discounted_gain,idcg,dcg,ndcg,mrr
0,7465,hair salon chair,Massage Chairs|Recliners,Furniture / Living Room Furniture / Chairs & S...,offers a wide selection of professional salon ...,fauxleathertype : pu|legheight-toptobottom:18|...,69.0,4.5,53.0,"[fauxleathertype : pu, legheight-toptobottom:1...",...,91.009596,salon chair,0,1,2.0,3.00,8.786905,8.10119,0.921962,1.0
1,25431,barberpub salon massage chair,Massage Chairs,Furniture / Living Room Furniture / Chairs & S...,salon chairs are a wonderful avenue for hairst...,supplierintendedandapproveduse : non residenti...,4.0,5.0,4.0,[supplierintendedandapproveduse : non resident...,...,82.237749,salon chair,0,2,2.0,1.50,8.786905,8.10119,0.921962,1.0
2,7468,mercer41 hair salon chair hydraulic styling ch...,Massage Chairs,Furniture / Living Room Furniture / Chairs & S...,mercer41 beauty offers a wide selection profes...,seatfillmaterial : foam|waterrepellant : no re...,1.0,5.0,1.0,"[seatfillmaterial : foam, waterrepellant : no ...",...,78.749867,salon chair,0,3,2.0,1.00,8.786905,8.10119,0.921962,1.0
3,39461,professional salon reclining massage chair,Massage Chairs,Furniture / Living Room Furniture / Chairs & S...,new and in a good condition . first-rate metal...,overalldepth-fronttoback:39.4|warrantylength:1...,NaN,NaN,NaN,"[overalldepth-fronttoback:39.4, warrantylength...",...,73.923359,salon chair,0,4,2.0,0.75,8.786905,8.10119,0.921962,1.0
4,9234,beauty salon task chair,NaN,Furniture / Office Furniture / Office Chairs,"applicable scene : office , home life , beauty...",overallheight-toptobottom:37|backcolor : brown...,NaN,NaN,NaN,"[overallheight-toptobottom:37, backcolor : bro...",...,72.375283,salon chair,0,5,1.0,0.20,8.786905,8.10119,0.921962,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,40247,winn hanging wine glass rack,Wine Racks,Kitchen & Tabletop / Tableware & Drinkware / B...,are you looking for a safe and decorative solu...,overallheight-toptobottom:1.5|overallwidth-sid...,305.0,5.0,187.0,"[overallheight-toptobottom:1.5, overallwidth-s...",...,72.749005,rack glass,487,6,0.0,0.00,8.786905,0.00000,0.000000,0.0
4796,40245,podgorni hanging wine glass rack,Wine Racks,Kitchen & Tabletop / Tableware & Drinkware / B...,display and protect your delicate wine or marg...,overallheight-toptobottom:1.5|stemwarecapacity...,6.0,4.0,6.0,"[overallheight-toptobottom:1.5, stemwarecapaci...",...,72.584869,rack glass,487,7,0.0,0.00,8.786905,0.00000,0.000000,0.0
4797,7151,bataan hanging wine glass rack,Wine Racks,Kitchen & Tabletop / Tableware & Drinkware / B...,hang your stemware in style with this charming...,stemwarecapacity:18|material : wood|design : h...,103.0,4.5,78.0,"[stemwarecapacity:18, material : wood, design ...",...,72.259416,rack glass,487,8,0.0,0.00,8.786905,0.00000,0.000000,0.0
4798,40251,wellman chiraz hanging wine glass rack,Wine Racks,Kitchen & Tabletop / Tableware & Drinkware / B...,add flair to your wine decor with this set of ...,style : modern & contemporary|overallwidth-sid...,175.0,5.0,107.0,"[style : modern & contemporary, overallwidth-s...",...,70.060043,rack glass,487,9,0.0,0.00,8.786905,0.00000,0.000000,0.0
4799,31842,prewitt hanging wine glass rack,Wine Racks,Kitchen & Tabletop / Tableware & Drinkware / B...,running out of space in your cabinets and atop...,producttype : wine glass rack|color : silver|o...,414.0,4.5,241.0,"[producttype : wine glass rack, color : silver...",...,69.810912,rack glass,487,10,0.0,0.00,8.786905,0.00000,0.000000,0.0

### Check results - Observe still healthy NDCG bump

NDCG still pretty good (not as good as sending the Literal list). But still pretty healthy increase.

In [32]:
from cheat_at_search.search import graded_bm25
ndcgs(graded_bm25).mean(), ndcgs(graded_fully_classified).mean()

(np.float64(0.5407553553417934), np.float64(0.5585788962651853))

In [33]:
deltas = ndcg_delta(graded_fully_classified, graded_bm25)

In [34]:
sig_improved = len(deltas[deltas > 0.1])
print(f"Num Significatly Improved: {sig_improved}")
deltas[deltas > 0.1]

Num Significatly Improved: 35

query
drum picture                                                       0.506435
non slip shower floor tile                                         0.458113
modern outdoor furniture                                           0.365533
twin bed frame                                                     0.359391
wood rack wide                                                     0.346159
desk for kids                                                      0.344262
liberty hardware francisco                                         0.292914
podium with locking cabinet                                        0.256063
outdoor lounge chair                                               0.248431
hardwood beds                                                      0.238179
storage dresser                                                    0.236147
china clock                                                        0.189044
wainscoting ideas                                                  0.182089
moen 5995 arbor one                                                0.179876
dark gray dresser                                                  0.175902
teal chair                                                         0.166283
family lamp                                                        0.161676
carpet 5x6                                                         0.158831
town & country living curtains                                     0.154089
zodiac pillow                                                      0.151741
acrylic clear chair                                                0.150386
oriental vanity                                                    0.149347
driftwood mirror                                                   0.139818
odum velvet                                                        0.139096
ayesha curry kitchen                                               0.131509
light and navy blue decorative pillow                              0.124690
medium size chandelier                                             0.119812
bedroom wall decor floral, multicolored with some teal (prints)    0.116651
closet storage with zipper                                         0.113806
small wardrobe grey                                                0.113806
auburn throw pillows                                               0.112541
industrial pipe dining  table                                      0.110419
wisdom stone river 3-3/4                                           0.102425
midcentury tv unit                                                 0.102425
outdoor welcome rug                                                0.100935
Name: ndcg, dtype: float64

sig_harmed = len(deltas[deltas < -0.1])
print(f"Num Significatly Harmed: {sig_harmed}")
print(f"Prop improved/harmed: {sig_improved / (sig_harmed + sig_improved)} | {sig_harmed / (sig_harmed + sig_improved)}")
deltas[deltas < -0.1]

### Look at a query

In [35]:
QUERY = "outdoor lounge cushions"
fully_classified(QUERY), fully_classified(QUERY).cat_subcat

(QueryClassification(keywords='outdoor lounge cushions', hallucinated_classification=['Outdoor / Outdoor Comfort & Decor / Cushions & Pillows / Lounge Cushions', 'Furniture / Outdoor Furniture / Lounge Chairs & Ottomans / Cushioned Lounge Chairs', 'Home Decor / Textiles / Outdoor Cushions & Pillows / Lounge Cushions', 'Garden & Patio / Outdoor Seating / Cushioned Lounge Seats', 'Recreation & Leisure / Poolside & Patio Cushions / Lounge Cushions']),
 {'Outdoor / Outdoor & Patio Furniture', 'Outdoor / Outdoor Décor'})

In [36]:
ground_truth_cat[ground_truth_cat['query'] == QUERY]

                       query category     count
179  outdoor lounge cushions           0.805556

In [37]:
graded_fully_classified[graded_fully_classified['query'] == QUERY][['product_name', 'category hierarchy', 'grade', 'score']]

,product_name,category hierarchy,grade,score
1790,classic outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,89.672464
1791,outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,87.930735
1792,iola outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,87.345481
1793,outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,86.526578
1794,make it rain cerulean indoor/outdoor chaise lo...,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,85.435493
1795,annoeska outdoor reclining chaise lounge with ...,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,85.104138
1796,french edge indoor/outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,83.353908
1797,achary outdoor reclining chaise lounge with cu...,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,82.629877
1798,alexandra outdoor reclining chaise lounge with...,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,82.133712
1799,cara indooroutdoor chaise lounge cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,81.857544

In [38]:
graded_bm25[graded_bm25['query'] == QUERY][['product_name', 'category hierarchy', 'grade', 'score']]

,product_name,category hierarchy,grade,score
1790,outdoor chaise lounge cushion,NaN,2.0,79.604047
1791,dorrington outdoor chaise lounge cushion,NaN,2.0,75.647597
1792,replacement pillows outdoor lounge chair cushion,NaN,2.0,75.266675
1793,indoor/outdoor sunbrella chaise lounge cushion,NaN,2.0,74.830837
1794,classic outdoor lounge chair cushion,Outdoor / Outdoor Décor / Outdoor Pillows & Cu...,2.0,74.672464
1795,tropical outdoor lounge chair cushion,NaN,2.0,73.328273
1796,outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,72.930735
1797,jermaine outdoor lounge chair cushion,NaN,2.0,72.379733
1798,iola outdoor reclining chaise lounge with cushion,Outdoor / Outdoor & Patio Furniture / Outdoor ...,1.0,72.345481
1799,jermaine outdoor chaise lounge cushion,NaN,2.0,72.293748